name = "BitShogi"
uuid = "a6e937b9-9d5b-4c7d-91b7-27c81cc004f7"
authors = ["sam-ghala <ghalayini.sj@gmail.com>"]
version = "0.1.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
HTTP = "1.10.19"
JSON3 = "1.14.3"
Random = "1.11.0"
Test = "1.11.0"
