name = "BitShogi"
uuid = "a6e937b9-9d5b-4c7d-91b7-27c81cc004f7"
authors = ["sam-ghala <ghalayini.sj@gmail.com>"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Random = "1.11.0"
Test = "1.11.0"
